### ISSUE TITLE
dat-js proposal

### ISSUE THREAD

**Issue by maxogden** [datproject/dat-js#35]
inspired by https://github.com/joehand/dat-js/issues/22, @karissa @joehand and I discussed and came up with this proposal, based on the API of [torrent-stream](https://npmjs.org/torrent-stream) and therefore also [webtorrent](https://npmjs.org/webtorrent)

### cli/desktop

- progress events (hyperdrive-stats)
- tcp/utp support (swarm module)
- filesystem access (read and write)
- leveldb
- size matters slightly less
- focused on downloading a single dat
- watching filesystem
- diffing filesystem
- whole files are stored random access
- fully seeds

### web app

- progress events (reading)
- websocket support
- HTML5 File API support (read only)
- memdb
- size matters
- either one or multiple dats per instance
- never buffer whole file into storage (only streaming download)
- does not really seed data, only downloads

### desktop

- size matters least
- multiple dats in one instance

some examples (may have errors)

```js
var dat = new Dat({db: leveldb})
dat.add('./mydat', function (repo) {
  repo.key
}) // existing dir, uses default leveldb

var dat = new Dat()
dat.add({key: 'blah', db: memdb}, function (repo) {
  repo.key
}) // in browser download

dat.add() // creates keys for you
dat.on('repo', function (repo) {
  // emitted when repo is ready to be used
  repo.key
  repo.privateKey
})

dat.repos // array of Repo instances

var watch = require('hyperdrive-import-files')
var stats = require('hyperdrive-stats')
var swarm = require('hyperdrive-archive-swarm')

var dat = new Dat()
dat.add('./mydat', {swarm: false, ignore: '*.jpg', resume: true, live: true}, function (repo) {
  if (repo.owner) var watcher = watch(repo)
  var emitter = stats(repo)
  var swarmer = swarm(repo)
  swarmer.pause()
  swarmer.resume()
})

var watch = require('some-file-watcher')
var dat = new Dat()
dat.add('./mydat', function (repo) {
    watch(repo.path, function (change) {
        repo.append(change.filename)
    })
    repo.pause()
    
})
```

## notes
https://github.com/juliangruber/hyperdrive-import-files/blob/master/index.js#L143
dat-js default read only use case
for more use cases have options to configure
default memdb
default swarm (? webrtc)
expose the hyperdrive

**Comment by maxogden** [comment]
curious for feedback from @mafintosh, @yoshuawuyts @juliangruber

**Comment by mafintosh** [comment]
@maxogden overall looks good!

Unsure about all the details but it seems this is just mostly composing a bunch of modules into something that is "easier" to use which I like.

Semi-related I'd hope this would end up being a module similar to https://github.com/maxogden/mississippi that more of less just requires a bunch of other stuff and composes it a bit.

**Comment by yoshuawuyts** [comment]
it reminds me a little of the hypercore API we were using yesterday. Given I haven't used any of the underlying packages too much I don't have a strong opinion on details, but if this was the API think I could def use it

**Comment by karissa** [comment]
Yes, @mafintosh , you've got it. We want to make something that is easy to use with default settings in the browser, but also can be easily customized and underlying modules replaced by setting something like `swarm:false`.

**Comment by mafintosh** [comment]
@karissa great stuff :+1:

**Comment by pfrazee** [comment]
I've written a bit of code in Beaker, which I would replace with dat-js if its possible. Some of it might be useful, or possibly not. The most relevant files are found in [this directory](https://github.com/beakerbrowser/beaker/tree/master/app/background-process/networks) and [this file](https://github.com/beakerbrowser/beaker/blob/master/app/background-process/dbs/archives.js).

It'll take me a little time, but I can spec out the APIs and requirements, if you want.

**Comment by karissa** [comment]
OK I spec'd out the api a bit more in this throwaway repo, 
https://github.com/karissa/dat-api

At some point lets move it to a datproject/dat-js branch

**Comment by karissa** [comment]
if someone wants to take it and go create a branch please feel free!!

**Comment by juliangruber** [comment]
+1 on making it one "manager" instance for multiple dats, makes more sense with the underlying mechanisms.

+1  on removing the importer and stats modules, but making them trivial to hook in, without necessarily coupling the interfaces to each other.

+1 overall, great work!
