### ISSUE TITLE
Stats for live updates incorrect often

### ISSUE THREAD

**Issue by joehand** [datproject/dat-js#8]
The stats on live updates need a lot of love for both sharing and downloading. I'll start collecting issues we can reproduce so they can get fixed.

**Comment by joehand** [comment]
This will be happening in [hyperdrive-stats](https://github.com/juliangruber/hyperdrive-stats)

**Comment by karissa** [comment]
yay

**Comment by joehand** [comment]
Closing this. Download stats were fixed with https://github.com/datproject/dat-js/pull/27. Sharing stats will be fixed and improved in hyperdrive-stats.
